<a href="https://colab.research.google.com/github/eileen-2/orm/blob/main/0104_%EB%A6%AC%EC%8A%A4%ED%8A%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. 리스트(List)란?

- [ , , , ] #CSV파일과 비슷
- 가변적(mutable)
- 순서가 있는 시퀀스 자료형, 배
- 위치의 특성 -> 정렬 가능
- 리스트 내의 원소들은 생성/ 변경 / 추가 /삭제 가능
- 항목변경: 인덱싱>새로운 값 할당

- 인덱싱 : 오류발생
- 슬라이싱 : 오류미발

>ex) 디렉터리에서 파일리스트, 회사에서 직원리스트, 메일함의 이메일 목록 등

리스트가 왜 필요할까요?

100명의 성적을 채점하기 위해서 지금까지 배웠던 지식으로는 100개의 변수를 만들어야 했습니다. x1, x2, x3…그것을 쉽게 구현한 것이 리스트라고 생각하시면 됩니다. 이를 배열이라고 하기도합니다.

In [5]:
#리스트의 필요성
x1=100
x2=200

x = [1, 2, 3]
y = ['apple', 'banana', 'cherry']

print(len(x))
print(len(y))

3
3


In [6]:
# 리스트의 장점: 여러가지 자료형을 넣을 수 있다
# 리스트 내부에 저장된 각 데이터를 "항목" 또는 "원소"
  # 0번째
z = [1, 'apple', 2.5, ['a', 'b'], (1, 2), '!']
print(z[0])

1


# 1.2 리스트의 수정 및 다차원 리스트

- 항목의 변경이 가능
- 다양한 자료형 담기 가능
- 다차원 리스트 구성 가능

데이터 분석과 같은 분야에서는 이러한 다차원 리스트를 이용하여 행렬을 표현하기도 합니다.
수학적 - 고차원 행령 -> 딥러닝/머신러닝 -> 다변량분석 -> 딥러닝의 많은 뉴럴네트워크


In [9]:
# 2.2 리스트 값 수정

a = [1, 2, 3, 4, 5]
a[0] = 10000 #인덱싱 설정하여 할당
print(a) #결과:1->10000

[10000, 2, 3, 4, 5]


In [11]:
# 문자열은 변경할 수 없다

s = 'licat'
print(s[0])
s[0] = 'k' #str 변경 불가 / 문자열 메서드 replace 같은거로 대체해야함.

l


TypeError: ignored

In [14]:
# 3. 리스트 안에 리스트(다차원 리스트)

b = [[10, 20, 30], [1, 2, 3]]
print(b[1][2]) # 출력: 3

3


In [16]:
print(b)

[[10, 20, 30], [1, 2, 3]]


In [18]:
#이런식으로 구성되어 있는 상태임(테이블 처럼)
'''
나이 직업구분
10      1
20      2
30      3
'''

'\n나이 직업구분\n10      1\n20      2\n30      3\n'

In [24]:
print(b[1]) # 2열
print(b[0]) # 1열
print(b[0][0]) # 1열 1행
print(b[0][1]) # 1열 2행
print(b[1][0]) # 2열 1

[1, 2, 3]
[10, 20, 30]
10
20
1


# 리스트 연산



In [28]:
# 리스트의 덧셈
a = [1, 2, 3, 4, 5]
b = [6, 7, 8]

print(a + b) # 출력: [1, 2, 3, 4, 5, 6, 7, 8]

[1, 2, 3, 4, 5, 6, 7, 8]


In [30]:
# 리스트
l = [1, 2, 3]
print(type(l))
print(l)
print(l * 3)
print(l + l)

<class 'list'>
[1, 2, 3]
[1, 2, 3, 1, 2, 3, 1, 2, 3]
[1, 2, 3, 1, 2, 3]


In [31]:
# numpy는 행렬 계산에 능하다.

import numpy as np

l = [1, 2, 3]
l = np.array(l)
print(l)
print(l * 3)
print(l + l)

[1 2 3]
[3 6 9]
[2 4 6]


In [35]:
# 중첩되지 않은 리스트의 곱셈은 값이 하나가 변경이 되어도 다른 값들이 변경이 되지 않습니다.
a = [1, 2, 3]
a = a * 3

a[0] = 1000
print(a)

[1000, 2, 3, 1, 2, 3, 1, 2, 3]


In [37]:
# 2.2 리스트 인덱싱 - 에러가 발생한다.

#리스트 에러 : 범위 초과
lst = [1, 2, 3, 4, 5]
print(lst[10])

IndexError: ignored

In [38]:
# 2.3 리스트 슬라이싱

#[start:stop:step]

In [40]:
# 슬라이싱 실습

l = [1, 2, 3, 4, 5]
print(l[:])     # 출력: [1, 2, 3, 4, 5]
print(l[::-1])  # 출력: [5, 4, 3, 2, 1]
print(l[::2])   # 출력: [1, 3, 5] 첫번째 인덱싱부터 두개씩 건너서
print(l[0:4][::-1]) # 출력: [4, 3, 2, 1]

[1, 2, 3, 4, 5]
[5, 4, 3, 2, 1]
[1, 3, 5]
[4, 3, 2, 1]


In [41]:
# 데이터가 크다. 내가 원하는대로 데이터를 추출하고 싶다.
# 1. 샘플링 -> 1억개 데이터 - > 천개! -> 리스트 슬라이싱! , 메서드! - > 1억개 데이터!

In [42]:
#슬라이싱은 에러가 나지 않는다

l = [1, 2, 3, 4, 5]
print(l[10:20]) # 출력: []

[]
