<a href="https://colab.research.google.com/github/eileen-2/orm/blob/main/0119_%EB%AC%B8%EC%A0%9C%ED%92%80%EC%9D%B4_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#프로그래머스 문제 풀이

In [ ]:
def (data):
    return
solution()

# 홀수 짝수 찾기
# https://school.programmers.co.kr/learn/courses/30/lessons/120824

In [8]:
def solution(date):
    짝수 = [i % 2 == 0 for i in data]
    홀수 = [i % 2 != 0 for i in data]
    return [sum(짝수), sum(홀수)]


In [7]:
def solution(data):
    count = 0
    for i in data:
        if i % 2 == 0:
            count += 1
        return [count, len(data)-count]


In [ ]:
def solution(num_list):
    answer = [0, 0]
    for i in num_list:
        answer[i % 2] += 1
    return answer

In [ ]:
# 좋은 풀이는 아닙니다.
# data의 가변 최대치를 봅니다.
def solution(data):
    짝수 = [i % 2 == 0 for i in data]
    return [sum(짝수), len(data) - sum(짝수)] # sum이 순회합니다.

In [9]:
def solution(data):
    짝수 = [i % 2 == 0 for i in data]
    갯수 = sum(짝수)
    return [갯수, len(data)-갯수]

# 머쓱이보다 키 큰 사람
# https://school.programmers.co.kr/learn/courses/30/lessons/120585


In [ ]:
#리스트에 리스트인 것은 언패킹해서 쓰세요. 코드 가독성 좋아짐.
def solution(data):
    count = 0
    for i in arry:
        if i > height:
            count += 1
        return count

In [ ]:
# filter는 len가 없습니다!!!!!!
def solution(arry, height):
    print(listfilter(lambda x: x> height, array))
        return

solution([149, 180, 192, 170], 167)

In [15]:
# filter는 len가 없습니다!
def solution(array, height):
    return len(list(filter(lambda x: x > height, array)))

solution([149, 180, 192, 170], 167)

# 왜 filter는 len이 없을까?
# 순회 돌기 전까지는 실행이 되지 않는 함수
# for와 같이 순회를 돌아야 그때서 각 원소 별로 접근
# 주문만 하고 아직 제조 되지 않은 커피 같은 존재
# 커피를 달라고 소리쳐야(순회, 형변환) 그때서야 제조가 됩니다

3

In [14]:
def solution(array, height):
    return(sum(map(lambda x: x>height, array)))

solution([149, 180, 192, 170], 167)

3

In [13]:
def solution(array, height):
     return sum([i > height for i in array])

solution([149, 180, 192, 170], 167)

3

# 숨어있는 숫자의 덧셈


https://school.programmers.co.kr/learn/courses/30/lessons/120851

In [ ]:
def solution():
    pass

solution("aAb1B2cC34oOp")

In [ ]:
# 오답, 그러나 이렇게도 많이 사용합니다.
def solution(my_string):
    count = 0 # if -> ture면 count에 저장해라.
    for i in my_string:
        if i.isdigit():
            count += 1

solution("aAb1B2cC34oOp")

In [18]:
def solution(my_string):
    result = 0
    for i in my_string:
        if i.isdigit():
            result += int(i)

    return result

solution("aAb1B2cC34oOp")

10

In [26]:
# 효율적이진 않지만, 문법 복습차원에서
def solution(my_string):
    return list(filter(str.isdigit, list(my_string)))


solution("aAb1B2cC34oOp")

['1', '2', '3', '4']

In [28]:
def solution(my_string):
    return filter(str.isdigit, my_string)


solution("aAb1B2cC34oOp")

In [31]:
# isdigit에 ()가 있고 없고의 차이는 무엇인가요?
def 함수(x):
    return x.isdigit()

def solution(my_string):
    return list(filter(str.isdigit, my_string)) # str에서 제공하는 isdigit함수에 my_string 인자가 하나씩 들어와서 True or false 판별해서 필터


solution("aAb1B2cC34oOp")

['1', '2', '3', '4']

In [37]:
def solution(my_string):
    return sum(map(lambda x: int(x) if x.isdigit() else False, my_string))

solution("aAb1B2cC34oOp")

10

In [41]:
# r은 raw 날 것의 라는 뜻임
# 실무에서 자주쓰는 용어 raw != low
# raw data 전달해줘: 가공하지 않은 순수 데이터를 달라는 얘기

r'hello\world'

print('hello\nworld')
print(r'hello\nworld')

hello
world
hello\nworld


In [42]:
import re
re.findall(r'[0-9]',"aAb1B2cC34oOp")

['1', '2', '3', '4']

In [44]:
import re

def solution(s):
    sum(map(int, re.findall(r'[0-9]', s))) #map은 정수형으로 형변환 가능, 리스트나 반복가능한 객체에 함수 적용할때.

solution("aAb1B2cC34oOp")

In [45]:
import re

def solution(s):
    return sum(map(int, (re.sub(r'[a-zA-Z]', '', s)))) # sub는 대체하기

solution('aAb1B2cC34oOp')

10

# 암호해독
https://school.programmers.co.kr/learn/courses/30/lessons/120892

In [46]:
def solution(cipher, code):
    return cipher[code-1::code]

solution("dfjardstddetckdaccccdegk", 4)
'''
문자열 슬라이싱은 [시작 인덱스:끝 인덱스:스텝] 형태로 사용합니다. 여기서 시작 인덱스는 슬라이싱을 시작할 위치, 끝 인덱스는 슬라이싱을 끝낼 위치 (하지만 이 인덱스 직전까지만 포함됩니다), 그리고 스텝은 몇 개의 요소를 건너뛰면서 가져올지를 결정하는 값이에요.

solution 함수에서 사용된 슬라이싱 cipher[code-1::code]를 분석해볼게요:

code-1은 슬라이싱이 시작될 인덱스를 의미합니다. code가 4이면, code-1은 3이 되겠죠. 파이썬은 0부터 인덱싱을 시작하므로, 실제로는 4번째 문자에서 슬라이싱이 시작됩니다.
두 번째 콜론(:) 뒤의 code는 스텝을 의미합니다. 여기서는 4이므로, 현재 인덱스에서 시작해서 매 4번째 문자를 가져옵니다.
끝 인덱스가 지정되지 않았으므로, 문자열의 끝까지 슬라이싱합니다.
예제 solution("dfjardstddetckdaccccdegk", 4)를 통해 설명드리면:

"dfjardstddetckdaccccdegk" 문자열에서 4번째 문자인 'a'부터 시작합니다.
여기서부터 4개의 문자를 건너뛰고 다음 문자를 가져옵니다: 'r', 's', 'd', 'e', 'k' (각각 인덱스 3, 7, 11, 15, 19에 해당합니다).
'''

'attack'

In [59]:
def solution(cipher, code):
    count = 1
    for i in cipher:
        if count == code:
            print(i)
            count = 0
        count += 1

solution("dfjardstddetckdaccccdegk", 4)

a
t
t
a
c
k


In [54]:
code = "dfjardstddetckdaccccdegk"
code[-1::2]

'k'

In [63]:
def solution(cipher, code):
    count = 1
    for i, j in enumerate(cipher, 1):
        if i % code == 0:
            print(j)

solution("dfjardstddetckdaccccdegk", 4)

a
t
t
a
c
k


In [75]:
# 3 7 11 15
# 이런 풀이는 권하지 않습니다.
def solution(cipher, code):
    result = ''
    for i in range(1, len(cipher) // code + 1):
        result += cipher[i * code - 1]
    return result

solution("dfjardstddetckdaccccdegk", 4)

'attack'

# 3 6 9 게임
https://school.programmers.co.kr/learn/courses/30/lessons/120891


In [78]:
def solution(order):
    order = str(order)
    return order.count('3') + order.count('6') +order.count('9')

solution('29423')

2

In [79]:
import re

re.findall(r'[369]','1231231234839291')

['3', '3', '3', '3', '9', '9']

In [80]:
import re


def solution(order):
    order = str(order)
    return len(list(re.findall(r'[369]', order)))

중복문자 제거하기
https://school.programmers.co.kr/learn/courses/30/lessons/120888

In [89]:
def solution(s):
    answer = ''
    for i in s:
        if i not in answer:
            answer += i
        return(answer)

solution('people')

'p'

In [91]:
def solution(my_string):
    return ''.join(dict.fromkeys(my_string)) # 딕셔너리는 키중복이 안된다를 이용함.

solution('people')

'peol'

A로 B 만들기
https://school.programmers.co.kr/learn/courses/30/lessons/120886


In [111]:
def reverse(n):
    if len(n) <= 1:
        return n
    return reverse(n[1:]) + n[0]

reverse("olleh")



'hello'

In [105]:
def solution(before, after):
    if len(before) != len(after):
        return 0
    return 1 if sorted(before) == sorted(after) else 0

solution('olleh', 'hello')

1

In [112]:
import collections

collections.Counter("olleh")
collections.Counter('olleh') == collections.Counter('hello')

True

In [117]:
def solution(before, after):
    a = list(after)
    for i in before:
        if i in a:
            a.remove(i)
        else:
            return 0
    if a:   # 없어도 맞긴하지만 냅둡시다
        return 0
    return 1

solution("olleh", "hello")


['h', 'e', 'l', 'l', 'o']


0

In [119]:
# 회문
'''
'hello' -> 'elloh' -> 'llohe'
'hello' -> 'ohell' -> 'lohel'
# collections.deque
'''
# 문제1, 'hello를 앞뒤로 이동시켜 'llohe'를 만들 수 있나요
'hellohello'

# 문제 2, 몇칸 이동했나요
'hellohello'.index('llohe')

2

저주의 숫자
https://school.programmers.co.kr/learn/courses/30/lessons/120871


In [120]:
# 십진수       3숫자마을
# 1                 1
# 2                 2
# 3                 4
# 4                 5
# 5                 7
# 6                 8
# 7                 10
# 8                 11
# 9                 14
# 10                16







In [ ]:
#[True, True, False...]

In [ ]:
#filter('3이 들어간 숫자', filter('3의배수인 숫자', [1,2,3,4,5,6,7,8,9,10]))

In [127]:
list(filter(lambda x: (x % 3 != 0) and ('3' not in str(x)), range(100)))[15-1]

25

In [128]:
def solution(num):
    return list(filter(lambda x: (x % 3 != 0) and ('3' not in str(x)), range(1000)))[num-1]

solution(15)

25

In [132]:
def solution(num):
    l = []
    for i in range(1000):
        if i % 3 != 0:
            l.append(i)
        elif '3' not in str(i):
            l.append(i)
    print(l)
solution(15)

[0, 1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32, 34, 35, 37, 38, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 124, 125, 126, 127, 128, 129, 130, 131, 133, 134, 136, 137, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 232, 233, 235, 2

진료순서정하기
https://school.programmers.co.kr/learn/courses/30/lessons/120835

In [142]:
# emergency     result
# [3, 76, 24]   [3, 1,2]


def solution(emergency):
    sorted_emergency = sorted(emergency, reverse=True)
    return [sorted_emergency.index(i) + 1 for i in emergency]


solution([3, 76, 24])

[3, 1, 2]

In [139]:
emergency = [3, 76, 24]
sorted_emergency = sorted(emergency, reverse = True)
sorted_emergency

[sorted_emergency.index(i)+1 for i in emergency]

[3, 1, 2]

In [140]:
data = ['제주', '경기', '전주'] # ['064', '031', '063']
data2 = {
    '제주': '064',
    '경기': '031',
    '전주': '063'
}

[data2[i] for i in data]

['064', '031', '063']

## 가까운 수
링크: https://school.programmers.co.kr/learn/courses/30/lessons/120890

In [ ]:
#[3, 10, 28] -> [17, 10, 8] 정렬문제->sorted문제(작거나 크거나 가까운 수)
#원하는 숫자: 20
#result : 28

In [148]:
l = [3, 10, 28]
sorted(l, key=lambda x:abs(x-20))[0] # 예외가 있을 수 있어서 절대값 abs처리

28

In [149]:
# 오류 같은 값이 있으면 더 작은 값이 반환되게
def solution(array, n):
    return sorted(array, key=lambda x: abs(x-20))[0]

In [151]:
#[3, 10, 28, 30, 12] -> [17, 10, 8, 10, 8] 정렬문제->sorted문제(작거나 크거나 가까운 수)
#원하는 숫자: 20
#result : 28

array = [3, 10, 28, 30, 12]
n = 20

sorted(array, key = lambda x: (abs(x-n), x))[0]

12

In [156]:
array = [3, 10, 28, 30, 12]
n = 20
'''
28 - 20 = 8
12 - 20 = -8

20 - 28 == -8
20 - 12 == 8
'''
sorted(array, key = lambda x: (abs(x-n), n-x))[0] #x와 n의 자리를 바꿔보면! 차이가 큰 순으로

28

k의 갯수
https://school.programmers.co.kr/learn/courses/30/lessons/120887



In [161]:
#i   j   k
#1   13  1

i = 1
j = 13
k = 1

str(list(range(i,j+1))).count(str(k)) #'[1, 11, 13]].count('1')

6

In [162]:
a = 10
b = 20

# swap

temp = a
a = b
b = temp

# python에서 사용하는 swap

a = 10
b = 20
a, b = b, a
a, b


(20, 10)

In [168]:
i = 1
j = 13
k = 1

count = 0
for temp in range(i, j):
    count += str(temp).count(str(k))

count

5

In [170]:
def solution(i, j, k):
    return str(list(range(i,j+1))).count(str(k)) #'[1, 11, 13]].count('1')

In [179]:
# 각 선분이 있는 곳의 총 길이의 합 문제
# [0, 5], [3, 5], [7, 10]

선 = [False] * 10
선

[False, False, False, False, False, False, False, False, False, False]

In [180]:
for i in range(0, 5):
    선[i] = True

선

[True, True, True, True, True, False, False, False, False, False]

In [181]:
for i in range(3, 5):
    선[i] = True

선

[True, True, True, True, True, False, False, False, False, False]

In [182]:
for i in range(7, 10):
    선[i] = True

선

[True, True, True, True, True, False, False, True, True, True]

In [183]:
sum(선)

8

In [189]:
a = 10; b= 10
a, b

(10, 10)

In [ ]:
#에라토스테네의 체: 소수판별: 알고리즘 문제로 내는 건....
소수 = [True] * 120
소수[0] = 소수[1] = False

for i in range(4, 120, 2):
    소수[i] = False

for i in range(6, 120, 3):
    소수[i] = False

for i in range(10, 120, 5):
    소수[i] = False

소수



In [ ]:
for 소수, 판별 in enumerate(소수):
    if 판별:
        print(소수)

https://100.pyalgo.co.kr/?page=23

In [ ]:
# ([1,3,5],[7,9,11][13, 15,17],7)

In [199]:
s = [[[1, 3, 5],[7, 9, 11],[13, 15, 17],7]]

sum(s, [])


[[1, 3, 5], [7, 9, 11], [13, 15, 17], 7]

In [200]:
import numpy as np

x = np.array([1, 2, 3])
x * 2

array([2, 4, 6])

In [205]:
s = [[1, 3, 5],[7, 9, 11],[13, 15, 17]]
s = np.array(s)
행, 렬 = np.where(s ==7) # 어떤 숫자의 위치 반환 where
행

array([1])

In [208]:
# 지뢰찾기 - 행령 -> numpy를 활용하면 쉽게 풀린다
x = [[0, 1, 0, 0],
    [0, 1, 0, 0],
    [0, 1, 0, 0],
    [0, 1, 0, 0]]


x = np.array(x)
np.where(x ==1)


(array([0, 1, 2, 3]), array([1, 1, 1, 1]))

In [213]:
x = [[0, 1, 0, 0],
     [0, 1, 0, 0],
     [0, 1, 0, 0],
     [0, 1, 0, 0]]

s = 0
for i in x:
    s += i.count(1)

s

4

In [217]:
x = [[0, 1, 0, 0],
     [0, 1, 0, 0],
     [0, 0, 0, 1]]

x = np.array(x)
x == 1  # true, false로 출력


array([[False,  True, False, False],
       [False,  True, False, False],
       [False, False, False,  True]])

In [219]:
x = [[0, 5, 2, 0],
     [0, 1, 3, 0],
     [2, 1, 0, 7]]

x = np.array(x)
x > 3

array([[False,  True, False, False],
       [False, False, False, False],
       [False, False, False,  True]])